<?= $this->doctype() ?>

<html xlmns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
    <head>
        <!-- outputting content from the Bootstrap -->
        <?= $this->headMeta(); ?>
        <?= $this->headTitle(); ?>
        <?= $this->headStyle(); ?>
        <?= $this->headLink(); ?>
        <?= $this->headScript(); ?>
    </head>

    <body>
        <h1 class="noDisplay">
            <?= $this->placeholder('Zend_View_Helper_HeadTitle'); ?>
        </h1>

        <!-- rendering the navigation menu -->
        <div id="headwrap" class="clearfix">
            <div class="right">
                <?= $this->render('_topnav.phtml') ?>
            </div>
            <div id="logo" class="left">
                <img src="/images/layout/logo.png" alt="Shop till you drop..." />
            </div>
        </div>

        <div id="contentWrap" class="clearfix">
            <div class="left categorylist">
                Category list
            </div>

            <div class="content left">
                <?= $this->layout()->content ?>
            </div>
        </div>

            <div id="footer" class="clearfix">
                <div class="left">
                    <span class="rss">
                        <a href="/rss" title="produce feed">RSS 2.0</a>
                    </span>
                </div>
                <div class="right">
                    &#169; 2008 Keith Pope
                </div>
            </div>
    </body>
</html>